# Download dataset

In [1]:
# Download dataset from Kaggle using kagglehub library
import kagglehub

path = kagglehub.dataset_download("aadimator/nyc-automated-traffic-volume-counts")

print("Path to dataset files:", path)

Downloading to /home/thomas/.cache/kagglehub/datasets/aadimator/nyc-automated-traffic-volume-counts/1.archive...

100%|██████████| 1.19G/1.19G [04:02<00:00, 5.26MB/s]

Extracting files...

Path to dataset files: /home/thomas/.cache/kagglehub/datasets/aadimator/nyc-automated-traffic-volume-counts/versions/1

# Initial dataset investigation

In [3]:
# Load the dataset using pandas
import pandas as pd

df = pd.read_csv(path + "/Automated_Traffic_Volume_Counts.csv")

In [4]:
df.shape

(27190511, 14)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27190511 entries, 0 to 27190510
Data columns (total 14 columns):
 #   Column     Dtype
---  ------     -----
 0   RequestID  int64
 1   Boro       str
 2   Yr         int64
 3   M          int64
 4   D          int64
 5   HH         int64
 6   MM         int64
 7   Vol        int64
 8   SegmentID  int64
 9   WktGeom    str
 10  street     str
 11  fromSt     str
 12  toSt       str
 13  Direction  str
dtypes: int64(8), str(6)
memory usage: 2.8 GB

In [6]:
df.head()

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
0,20856,Queens,2015,6,23,23,30,9,171896,POINT (1052296.600156678 199785.26932711253),94 AVENUE,207 Street,Francis Lewis Boulevard,WB
1,21231,Staten Island,2015,9,14,4,15,6,9896,POINT (942668.0589509147 171441.21296926),RICHMOND TERRACE,Wright Avenue,Emeric Court,WB
2,29279,Bronx,2017,10,19,4,30,85,77817,POINT (1016508.0034050211 235221.59092266942),HUNTS POINT AVENUE,Whittier Street,Randall Avenue,NB
3,27019,Brooklyn,2017,11,7,18,30,168,188023,POINT (992925.4316054962 184116.82855457635),FLATBUSH AVENUE,Brighton Line,Brighton Line,NB
4,26734,Manhattan,2017,11,3,22,0,355,137516,POINT (1004175.9505178436 247779.63624949602),WASHINGTON BRIDGE,Harlem River Shoreline,Harlem River Shoreline,EB

In [10]:
df.tail()

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
27190506,28843,Queens,2019,1,11,3,30,13,48625,POINT (1010498.7141876142 198418.68389121862),FOREST AVENUE,Greene Avenue,Bleecker Street,NB
27190507,21109,Brooklyn,2015,9,28,18,45,65,45144,POINT (1007888.490398333 194036.05423851966),IRVING AVENUE,Grove Street,Myrtle Avenue,SB
27190508,23455,Queens,2016,5,23,13,30,55,149068,POINT (1024888.1767334475 211528.3190361287),111 STREET,48 Avenue,47 Avenue,NB
27190509,22517,Bronx,2016,3,19,9,0,82,89528,POINT (1026078.0476007946 269670.6741176347),WHITE PLAINS ROAD,East 243 Street,Dead end,SB
27190510,10450,Queens,2012,10,19,0,30,20,69002,POINT (1009571.4 220310.5),23 AV,38 ST,STEINWAY ST,SB

In [11]:
df.describe()

,RequestID,Yr,M,D,HH,MM,Vol,SegmentID
count,2.719051e+07,2.719051e+07,2.719051e+07,2.719051e+07,2.719051e+07,2.719051e+07,2.719051e+07,2.719051e+07
mean,1.933671e+04,2.014698e+03,7.025961e+00,1.564600e+01,1.151098e+01,2.246823e+01,1.068197e+02,3.195813e+05
std,8.122612e+03,2.802874e+00,3.317061e+00,8.187659e+00,6.924898e+00,1.677890e+01,1.567890e+02,1.404841e+06
min,1.100000e+03,2.000000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00,4.400000e+01
25%,1.257600e+04,2.013000e+03,4.000000e+00,9.000000e+00,6.000000e+00,0.000000e+00,2.000000e+01,3.636800e+04
50%,2.025100e+04,2.015000e+03,7.000000e+00,1.600000e+01,1.200000e+01,1.500000e+01,5.900000e+01,7.899100e+04
75%,2.629100e+04,2.017000e+03,1.000000e+01,2.200000e+01,1.800000e+01,3.000000e+01,1.300000e+02,1.515990e+05
max,3.241800e+04,2.020000e+03,1.200000e+01,3.100000e+01,2.300000e+01,4.500000e+01,3.276700e+04,9.017093e+06

# Quality check

## Duplicates

In [ ]:
duplicated_rows = df[df.duplicated()]
duplicated_rows

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction
27078,31075,Staten Island,2019,10,14,17,45,107,8070,POINT (945865.9116432326 153828.1839704478),ROCKLAND AVENUE,Dead End,Brielle Avenue,EB
44163,9796,Queens,2011,3,31,20,45,73,51632,POINT (1026712.1 187506.5),ROCKAWAY BLVD APPROACH TO 93RD ST,92 ST,93 ST,EB
61865,26997,Brooklyn,2017,5,10,14,45,179,167004,POINT (1001951.0772225239 166131.556441433),KINGS HIGHWAY,Dead end,Flatbush Avenue,WB
69980,17657,Manhattan,2014,7,28,20,0,114,35875,POINT (990439.6 218452.3),CENTRAL PARK S,7 AV/C P 7 AV APPR,CENTER DR/AVE OF THE AMERICAS,EB
70843,15389,Manhattan,2013,7,28,16,30,101,158627,POINT (999220.5 229230.3),PARK AV,E 111 ST,E 110 ST,SB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27190218,21151,Manhattan,2016,2,29,22,30,155,139555,POINT (992651.6 217358.4),PARK AV,E 60 ST,E 59 ST,SB
27190249,17759,Manhattan,2014,8,2,5,15,26,37275,POINT (991736 229133.2),WEST END AV,W 96 ST,W 97 ST,SB
27190259,19316,Brooklyn,2015,4,17,10,45,65,22514,POINT (986960.5081405716 185616.9106953816),3 STREET BRIDGE,3 Street,3 Street,EB
27190447,28591,Bronx,2017,11,15,16,0,211,146585,POINT (1014364.2586928633 253211.53413322437),EAST FORDHAM ROAD,Dead end,Webster Avenue,EB
27190490,11539,Bronx,2013,1,19,6,15,8,78903,POINT (1016006.6 242238.9),W FARMS RD,JENNINGS ST,E 172 ST,SB

In [17]:
df_unique = df.drop_duplicates()
df_unique.shape

(26874241, 14)

In [ ]:
df_unique.nunique()

RequestID     7090
Boro             5
Yr              16
M               12
D               31
HH              24
MM               4
Vol           4016
SegmentID    14953
WktGeom      20463
street        6750
fromSt        6421
toSt          5915
Direction        6
dtype: int64

## Borough distribution

In [18]:
df_unique.groupby("Boro").size()

Boro
Bronx            4487305
Brooklyn         7912290
Manhattan        6010776
Queens           6926347
Staten Island    1537523
dtype: int64

## Time distribution

In [19]:
df_unique.groupby("RequestID").size().mean()

np.float64(3790.443018335684)

In [40]:
rec_per_day = df_unique.groupby(["Yr", "M", "D"]).size()
rec_per_day = rec_per_day.reset_index(name="Cnt")
rec_per_day

        Yr   M   D    Cnt
0     2000   1   1    189
1     2000   1   2    192
2     2000   1   3    192
3     2000   1   4    192
4     2000   1   5    192
...    ...  ..  ..    ...
4074  2020  11  18  11808
4075  2020  11  19  11808
4076  2020  11  20  10848
4077  2020  11  21  10848
4078  2020  11  22  10848

[4079 rows x 4 columns]

In [41]:
rec_per_day["date"] = pd.to_datetime(rec_per_day["Yr"].astype(str) + "-" + rec_per_day["M"].astype(str) + "-" + rec_per_day["D"].astype(str))
rec_per_day = rec_per_day.sort_values("date") # Looks like already the case but let's make sure
rec_per_day

        Yr   M   D    Cnt       date
0     2000   1   1    189 2000-01-01
1     2000   1   2    192 2000-01-02
2     2000   1   3    192 2000-01-03
3     2000   1   4    192 2000-01-04
4     2000   1   5    192 2000-01-05
...    ...  ..  ..    ...        ...
4074  2020  11  18  11808 2020-11-18
4075  2020  11  19  11808 2020-11-19
4076  2020  11  20  10848 2020-11-20
4077  2020  11  21  10848 2020-11-21
4078  2020  11  22  10848 2020-11-22

[4079 rows x 5 columns]

In [44]:
import plotly.express as px

fig = px.line(
    rec_per_day,
    x="date",
    y="Cnt",
    title="Traffic recordings per day",
    labels={"date": "Date", "Cnt": "Number of recordings"}
)

fig.update_traces(
    hovertemplate="Date: %{x|%Y-%m-%d}<br>Recordings: %{y}<extra></extra>"
)

fig.show()

In [58]:
all_days = pd.date_range("2010-01-01", "2020-12-31", freq="D")
missing_days = set(all_days.date) - set(rec_per_day["date"].dt.date)
len(missing_days)

557

In [59]:
len(missing_days) / len(all_days) * 100

13.862618218018916

In [60]:
missing_series = pd.Series(pd.to_datetime(list(missing_days)))
missing_per_year = missing_series.dt.year.value_counts().sort_index()
missing_per_year

2010     14
2011     32
2012     16
2013     17
2014     18
2015     34
2016     24
2017     27
2018     82
2019     36
2020    257
Name: count, dtype: int64

## Time of the day distribution (per year)

In [65]:
df_unique["minute_of_day"] = df_unique["HH"] * 60 + df_unique["MM"]
df_unique.head()

,RequestID,Boro,Yr,M,D,HH,MM,Vol,SegmentID,WktGeom,street,fromSt,toSt,Direction,minute_of_day
0,20856,Queens,2015,6,23,23,30,9,171896,POINT (1052296.600156678 199785.26932711253),94 AVENUE,207 Street,Francis Lewis Boulevard,WB,1410
1,21231,Staten Island,2015,9,14,4,15,6,9896,POINT (942668.0589509147 171441.21296926),RICHMOND TERRACE,Wright Avenue,Emeric Court,WB,255
2,29279,Bronx,2017,10,19,4,30,85,77817,POINT (1016508.0034050211 235221.59092266942),HUNTS POINT AVENUE,Whittier Street,Randall Avenue,NB,270
3,27019,Brooklyn,2017,11,7,18,30,168,188023,POINT (992925.4316054962 184116.82855457635),FLATBUSH AVENUE,Brighton Line,Brighton Line,NB,1110
4,26734,Manhattan,2017,11,3,22,0,355,137516,POINT (1004175.9505178436 247779.63624949602),WASHINGTON BRIDGE,Harlem River Shoreline,Harlem River Shoreline,EB,1320

In [66]:
dist_day = (
    df_unique
    .groupby(["Yr", "minute_of_day"])
    .size()
    .reset_index(name="Cnt")
)
dist_day

        Yr  minute_of_day   Cnt
0     2000              0    18
1     2000             15    19
2     2000             30    20
3     2000             45    20
4     2000             60    20
...    ...            ...   ...
1459  2020           1365  4581
1460  2020           1380  4581
1461  2020           1395  4578
1462  2020           1410  4581
1463  2020           1425  4580

[1464 rows x 3 columns]

In [68]:
fig = px.line(
    dist_day,
    x="minute_of_day",
    y="Cnt",
    color="Yr",
    title="Distribution of recordings during the day by year",
    labels={
        "minute_of_day": "Minute of day",
        "Cnt": "Number of recordings",
        "Yr": "Year"
    }
)

fig.show()

Clear necessary pre-processing. 

Chose later start date and do not include 2020.

Good daytime distribution.

# Ideas of exploration

NYC interactive map with colored road depending on use.

Explore effects of main NYC events (marathon etc. (if recording at these dates)).

Explore effects of holidays/weekends.

Explore effect of time of the day.

Possibility to fetch more recent data from: https://data.cityofnewyork.us/Transportation/Automated-Traffic-Volume-Counts/7ym2-wayt/data_preview. 

Don't forget to cite dataset!